backend:
  name: git-gateway
  branch: master

media_folder: static/images/uploads
public_folder: /images/uploads

site_url:
#logo_url:

publish_mode: editorial_workflow

collections:
  - label: "Pages"
    name: "pages"
    editor:
      preview: false
    files:
      