backend:
  name: git-gateway
  branch: master

media_folder: static/images/uploads
public_folder: /images/uploads

site_url: https://www.operationgetout.org/
#logo_url:

publish_mode: editorial_workflow

collections:
  - label: "Pages"
    name: "pages"
    editor:
      preview: false
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        preview_path: /
        fields:
          - { label: Header Headline, name: headerHeadline, widget: string }
          - { label: Header Sub Headline, name: headerSubHeadline, widget: string }
          - { label: Who We Are Paragraph 1, name: whoWeAreCopy1, widget: markdown }
          - { label: Who We Are Paragraph 2, name: whoWeAreCopy2, widget: markdown }
          - { label: Who We Are Paragraph 3, name: whoWeAreCopy3, widget: markdown }
          - { label: Events Paragraph, name: eventsCopy, widget: markdown }
          - { label: Donations Paragraph, name: donationsCopy, widget: markdown }
          - { label: Our Story Eyebrow, name: ourStoryEyebrow, widget: string }
          - { label: Our Story Headline 1, name: ourStoryHeadline1, widget: string }
          - { label: Our Story Paragraph 1, name: ourStoryCopy1, widget: markdown }
          - { label: Our Story Headline 2, name: ourStoryHeadline2, widget: string }
          - { label: Our Story Paragraph 2, name: ourStoryCopy2, widget: markdown }
          - { label: Testimonials Headline, name: testimonialsHeadline, widget: string }
          - { label: Testimonials Sub Headline, name: testimonialsSubHeadline, widget: string }

          - label: Testimonials
            name: testimonials
            label_singular: testimonial
            widget: list
            fields:
              - { label: Quote, name: quote, widget: string }
              - { label: Attribution, name: attribution, widget: string }
              - { label: Title, name: title, widget: string }
              - { label: Subtitle, name: subtitle, widget: string }

  - label: Team
    name: team-members
    editor:
      preview: false
    label_singular: Team Member
    format: frontmatter
    folder: content/team-members
    file: 'content/team-members.md'
    preview_path: /
    create: true
    identifier_field: name
    fields:
      - { label: Name, name: name, widget: string }
      - { label: Bio, name: bio, widget: text }

  - label: Events
    name: events
    editor:
      preview: false
    label_singular: Event
    format: frontmatter
    folder: content/events
    file: 'content/events.md'
    preview_path: /
    create: true
    identifier_field: name
    fields:
      - { label: Date Start (Day), name: dateStart, widget: datetime, format: 'YYYY-MM-DD' }
      - { label: Date End (Day), name: dateEnd, widget: datetime, format: 'YYYY-MM-DD' }
      - { label: Title, name: title, widget: string }
      - { label: Location, name: location, widget: string }
      - { label: Image, name: image, widget: image }
      - { label: Button Text, name: buttonText, widget: string }
      - { label: Button Url, name: url, widget: string }
      - { label: Body, name: body, widget: markdown }

      - label: Images
        name: images
        label_singular: image
        widget: list
        max: 8
        fields:
          - { label: Image , name: image, widget: image }
